---
title: "Web Scraping Reviews"
format: html
---

## Loading Packages

```{r}
#| output: false
library(tidyverse)
library(rvest)
```

## Figure out initial scraping code

```{r}
restaurant_home_link <- 
  # "https://www.yelp.com/biz/el-vaquero-mexican-restaurant-columbus-10"
  "https://www.yelp.com/biz/el-vaquero-mexican-restaurant-columbus-15"
```

#### Get the count of pages for the restaurant.

```{r}
page <- read_html(restaurant_home_link)

page_count <- 
  page %>% 
  html_element("#reviews 
               div.border-color--default__09f24__NPAKY.text-align--center__09f24__fYBGO 
               span.css-chan6m") %>% 
  html_text() %>% 
  str_remove("1 of ") %>% 
  as.numeric()
```

#### Make list of URLs.

It looks like Yelp shows 10 reviews per page and each page's URL says the number of review it starts on. (E.g., page 2's URL ends in "start=10".

```{r}
links <-
  paste0(restaurant_home_link,
         "?start=",
         seq(0, (page_count - 1) * 10, 10),
         "&sort_by=date_asc")
```

#### Get usernames

```{r}
#page <- read_html(links[16])

usernames <- 
  page %>% 
  html_elements("#reviews > section > div.css-79elbk.border-color--default__09f24__NPAKY li.margin-b5__09f24__pTvws.border-color--default__09f24__NPAKY") %>% 
  html_element("a.css-1m051bw") %>% 
  html_text()
```

#### Get user location

```{r}
user_locations <- 
  page %>% 
  html_elements("#reviews > section > div.css-79elbk.border-color--default__09f24__NPAKY li.margin-b5__09f24__pTvws.border-color--default__09f24__NPAKY") %>% 
  html_element("span.css-qgunke") %>% 
  html_text()
```

#### Get ratings

```{r}
ratings <- 
  page %>% 
  html_elements("#reviews > section > div.css-79elbk.border-color--default__09f24__NPAKY li.margin-b5__09f24__pTvws.border-color--default__09f24__NPAKY") %>% 
  html_element("div.arrange-unit__09f24__rqHTg.border-color--default__09f24__NPAKY span div") %>% 
  html_attr("aria-label") %>% 
  str_remove(" star rating") %>% 
  as.numeric()
```

#### Get date of review

```{r}
dates <- 
  page %>% 
  html_elements("#reviews > section > div.css-79elbk.border-color--default__09f24__NPAKY li.margin-b5__09f24__pTvws.border-color--default__09f24__NPAKY") %>% 
  html_element("span.css-chan6m") %>% 
  html_text() %>% 
  as.Date("%m/%d/%Y")
```
